project:
  type: website
  pre-render: download_resources.R
  resources:
    - "*.sqlite"
    - libs/

website:
  title: "multised (merged)"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/seafood-hazards/multised-merged
        aria-label: GitHub
    left:
      - text: "Home"
        href: index.qmd
      - text: "DB Design"
        menu:
          - text: "DB Schema (Merged)"
            href: db-schema-merged.qmd
          - text: "DB Schema (Aquaculture)"
            href: db-schema-aquaculture.qmd
      - text: "Analyses"
        menu:
          - text: "Data Categories"
            href: data-categories.qmd
          - text: "Outlier Flagging"
            href: outlier-flagging.qmd
      - text: "Explore"
        menu:
          - text: "Merged Tables"
            href: merged-tables.qmd
          - text: "Aquaculture Tables"
            href: aquaculture-tables.qmd
          - text: "Element Map"
            href: element-map.qmd
          - text: "Location Map"
            href: location-map.qmd
          - text: "Grain Size Map"
            href: grain-size-map.qmd
          - text: "Aquaculture Map"
            href: aquaculture-map.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: kable
    include-in-header: header.html

execute:
  echo: false
  warning: false
  message: false
